apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinch

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
  - gateway-ingress.yaml
  - gateway-hpa.yaml
  - vllm-service.yaml


