apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: cinch
  labels:
    app.kubernetes.io/name: cinch-gateway
    app.kubernetes.io/component: gateway
type: Opaque
stringData:
  GATEWAY_API_KEY: "cinch-prod-key"
